$(document).ready(function(){
	var html = [
'<div class="gutter-size"></div>',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result1.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Lorem ipsum dolor</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result2.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Sit amet dolor is</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result3.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Vestibulum libero massa</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result4.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Etiam sem odio</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result5.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result6.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Sed magna lacus</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result7.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Proin in nulla</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result8.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Pellentesque gravida</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result9.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Donec placerat vulputate</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result10.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Mauris hendrerit</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result11.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Sed semper lectus</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result12.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Fusce condimentum</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result13.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Lorem ipsum dolor</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result14.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Sit amet dolor is</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result15.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Vestibulum libera massa</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                               <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result16.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>        ',
'                                <p><a href="#">Etiam sem odio</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result17.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result18.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result19.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result20.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result21.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result22.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result23.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result24.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result25.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result26.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result27.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->',
'                            ',
'                            <!-- Start result-item -->',
'                            <div class="result-item  nested-item">',
'                                <div class="result-item-inner">',
'                                    <div>',
'                                        <a href="photo-view.html">',
'                                            <img src="img/result28.png" alt="Result img" />',
'                                        </a>',
'                                        <div class="result-hover">',
'                                            <ul class="clearfix">',
'                                                <li class="result-lightbox">',
'                                                    <span></span>',
'                                                    <ul class="result-lightbox-inner">',
'                                                        <li><a href="#">My Media</a><small>(3)</small></li>',
'                                                        <li><a href="#">List One</a><small>(14)</small></li>',
'                                                        <li><a href="#">List Two</a><small>(7)</small></li>',
'                                                        <li>',
'                                                            <form action="#" method="post">',
'                                                                <input type="text" name="newlightbox" value="" placeholder="New lightbox" />',
'                                                                <input type="submit" name="newlightbox-submit" value="save" class="btn blue-btn" />',
'                                                            </form>',
'                                                        </li>',
'                                                    </ul>',
'                                                </li>',
'                                                <li class="result-download">',
'                                                    <span></span>',
'                                                </li>',
'                                                <li class="result-upload">',
'                                                    <span class="share-btn"></span>',
'                                                    <div class="share-content-inner">',
'                                                        <input type="text" name="share-input" placeholder="http://www.domain.com/" value="" />',
'                                                        <a href="#" class="btn blue-btn">copy</a>',
'                                                        <p class="date-title">link accessible until</p>',
'                                                        <div class="select-date"></div>',
'                                                    </div>',
'                                                </li>',
'                                            </ul>',
'                                        </div>',
'                                    </div>',
'                                </div>',
'                                <p><a href="#">Aliquam erat volutpat</a></p>',
'                            </div>',
'                            <!-- End result-item -->'
].join('');
	var currentPage=$('.current').html();
	var isoOptions = {
	  	itemSelector : '.result-item',
		percentPosition : true,
		layoutMode : 'masonry',
		masonry : {
			gutter : '.gutter-size'
		}
	};
	
	// initialize Isotope
	var $grid = $('.result-inner').isotope( isoOptions );
	var isActive = true;
	var elem = $('.result-inner');
	
	$('.next').on('click',function(){
		
		$('.prev').closest('li').removeClass('disabled');
		$('.result-inner').children().hide().promise().done(function() {
			
		    $('.result-inner').children().remove();
		    $('.result-inner').append(html);
		    $('.result-inner').show();
			currentPage++;
			$('.current').html(currentPage);
			
			$('.result-item').each(function(){
				var elImg = $(this).find('img');
				var imgSrc = elImg.attr('src');
				elImg.closest('a').css({
					'background-image':'url(' + imgSrc + ')',
				});
				
			});
		});
		
		$('.result-inner .result-item').each(function(){
			var elImg = $(this).find('img');
			var imgW = elImg.width();
			var imgH = elImg.height();
			
			if( imgW > imgH ) {
				elImg.width('100%');
			}
		});
		
    	setTimeout(function(){
	    	$('.result-inner.nested').isotope('destroy'); // destroy
    		$('.result-inner.nested').isotope( isoOptions ); // re-initialize
		}, 150);

	});
	$('.mobile-load').on('click',function(e){
			e.preventDefault();
		    $('.result-inner').append(html).show();	
			
    		setTimeout(function(){
    			$('.result-inner.nested').isotope('destroy'); // destroy
    			$('.result-inner.nested').isotope( isoOptions ); // re-initialize
    		}, 300);
    		$('.result-item').each(function(){
				var elImg = $(this).find('img');
				var imgSrc = elImg.attr('src');
				elImg.closest('a').css({
					'background-image':'url(' + imgSrc + ')',
				});
				
			});
	});
		
	$('.prev').on('click',function(){
		
		if($('.current').html() == '2'){
			$('.prev').closest('li').addClass('disabled');
		}
		
		$('.result-inner .result-item').each(function(){
			var elImg = $(this).find('img');
			var imgW = elImg.width();
			var imgH = elImg.height();
			
			if( imgW > imgH ) {
				elImg.width('100%');
			}
		});
		
		if(currentPage>1){
			$('.result-inner').children().hide().promise().done(function() {
			    $('.result-inner').children().remove();
			    $('.result-inner').append(html);
			    $('.result-inner').show();
			    if(currentPage>1){
			    	currentPage--;
					$('.current').html(currentPage);
					
					setTimeout(function(){
				    	$('.result-inner.nested').isotope('destroy'); // destroy
			    		$('.result-inner.nested').isotope( isoOptions ); // re-initialize
		    		}, 150);
				    	
			  	}
			  	
			  	$('.result-item').each(function(){
					var elImg = $(this).find('img');
					var imgSrc = elImg.attr('src');
					elImg.closest('a').css({
						'background-image':'url(' + imgSrc + ')',
					});
					
				});
			});
		}
	});	
});